name: Generate Snake Animation

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: AzizbekShokirov
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
